AllCops:
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
